export const GET_ALL_CURRENCIES_REQUEST = "GET_ALL_CURRENCIES_REQUEST";
export const GET_ALL_CURRENCIES_SUCCESS = "GET_ALL_CURRENCIES_SUCCESS";
export const GET_ALL_CURRENCIES_FAILED = "GET_ALL_CURRENCIES_FAILED";
export const ADD_CURRENCY = "ADD_CURRENCY";
export const REMOVE_CURRENCY = "REMOVE_CURRENCY";
